AI_car_01:
  STEERING_GAINS: [-0.82879, 0.46146] #[1/rad] [1] used for delta-> control input conversion
  MOTOR_LIMIT: 0.1 # The absolute limit of the motors reference input that normally ranges from -1 to 1


RC_car_02:
  STEERING_GAINS: [-1, 0.5] #[1/rad] [1] used for delta-> control input conversion
  MOTOR_LIMIT: 0.1 # The absolute limit of the motors reference input that normally ranges from -1 to 1
