car_id: "RC_car_01"
angle_offset: 0.4651
angle_gain: 1

vesc_driver_node:
  car_id: "RC_car_01"
  port: /dev/sensors/vesc

vrpn_client_node:
  server: 192.168.1.141
  car_id: "RC_car_01"
  update_frequency: 50.0 # should match with state_observer_node

state_observer_node:
  cutoff: 2.0
  sampling_freq: 50.0 # should match with vrpn_client_ros

