---
# ROS network configuration data
ROS_MASTER_URI: http://192.168.1.77:11311
ROS_IP: 192.168.1.13


# ODE solver
SOLVER: "RK45" # ODE solver

# system frequency
FREQUENCY: 40.0

# dynamic single track vehicle model parameters
vehicles:
  AI_car_01:
    #init_pose: [0,  0,  0.59]  #-0.5931982357423143] # [1.8, -0.2,-3]
    init_pose: [-1.5800985436735742,  1.5166405007096615,  -0.59]  #-0.5931982357423143] # [1.8, -0.2,-3]
  #  # [ x[m], y[m], phi[rad] ]

    control:
      LATERAL_CONTROL_GAINS: # TODO: add details on the control algorithms
        k1: [-0.0000,0.0002,-0.0013,0.0225]
        k2: [-0.0089,0.0691,-0.2403,0.8267]
        k3: [0.0026,-0.0667,0.4328,-0.0604]
        #k1: [-0.0006,0.0051,-0.0170,0.1215]
        #k2: [-0.0494,0.3184,-0.7847,3.2132]
        #k3: [0.0350,-0.3029,1.0589,-0.1582]
      LONGITUDINAL_CONTROL_GAINS:
        k1: [0.0001,-0.0014,0.0908]
        k2: [-0.0025,0.0298,0.0095]
    # Specify custom model parameters here!
    # If no custom paramters are provided the default_vehicle_model will be used!
    #m:
    #l_f:
    #l_r:
    #I_z:
    #C_m1:
    #C_m2:
    #C_m3:
    #C_f:
    #C_r:
    
  AI_car_02:
    init_pose: [1,1,0]
  
  AI_car_03:
    init_pose: [-1,-1,0]


default_vehicle_model: # default model of the simulator
  # physical parameters
  m: 2.923 # [kg]
  l_f: 0.163 # [m]
  l_r: 0.168 # [m]
  I_z: 0.0796 # [kg m^2]

  # drivetrain parameters
  C_m1: 61.383 # [N]
  C_m2: 3.012 # [Ns/m]
  C_m3: 0.604 # [N]

  # tire parameters
  C_f: 41.7372 # [N/rad]
  C_r: 29.4662 # [N/rad]

  delta_max: 0.5 # [1]

  d_max: 0.2
