---
# list of vehicles in the fleet
fleet: ["RC_car_01", "RC_car_02", RC_car_03]

# ODE solver
solver: "RK45" # ODE solver

# dynamic singel track vehicle model parameters
vehicle_models:
  default_model: # default model of the simulator.
  
    # physical parameters
    m: 2.923 # [kg]
    l_f: 0.163 # [m]
    l_r: 0.168 # [m]
    I_z: 0.0796 # [kg m^2]
  
    # drivetrain parameters
    C_m1: 41.7960 # [N]
    C_m2: 2.0152 # [Ns/m]
    C_m3: 0.4328 # [N]

    # tire parameters
    C_f: 41.7372 # [N/rad]
    C_r: 29.4662 # [N/rad]
  
  # Create custom models here for each vehicle to override the default model
  #car_ID:
  #  m:
  #  l_f:
  #  l_r:
  #  I_z:
  #  C_m1:
  #  C_m2:
  #  C_m3:
  #  C_f:
  #  C_r: